highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://sandippandey.github.io
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Sandip Pandey's Resume
name: Sandip Pandey
email: sandippandeynp@gmail.com
email_full: mailto:youremail@me.com
website: github.io/sustain
website_full: https://sandipnp.github.io/sustain
github: trending
twitter: twitter
mobile: +358442090191
google_maps: https://www.google.com/maps/place/Keikarinkuja+2a,+01510+Vantaa/@60.2883485,24.9572679,17z/data=!3m1!4b1!4m5!3m4!1s0x468df806b5ffd4d9:0xb1c4b7b289b98f32!8m2!3d60.2883459!4d24.9594566
address:
  street: Keikarinkuja 2 A 12
  postcode: 01510
  city: Vantaa
  country: Finland
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
